---
title: "2_DataCleaning"
output: html_document
date: "2024-10-22"
---

##Step 0. Set up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## upload necessary packages
library(ggplot2)
library(tidyverse)
library(ggpubr)
library(lubridate)

## upload necessary data
# tick data
master <- read.csv("data/clean/lizardburden_master_2007_2022_20230627.csv")

# climate data
climate_full <- read.csv("data/clean/full_climate_summaries_dailymonthlyquarterly_20241023.csv") # for merging with tick
climate_daily <- read.csv("data/gridmet/csv/clean/merged_0722_petprsphtmmntmmx_daily_wide.csv") # for figures
climate_monthly <- read.csv("data/gridmet/csv/clean/merged_0722_petprsphtmmntmmx_monthly_wide.csv") # for figures

# climate regions
clim_regions <- read.csv("data/climregion_coords.csv")

```

##Step 1. Format data
```{r}
## climate regions
clim_regions_slim <- clim_regions %>% 
  dplyr::select(location, climregion)

## lizard data
master_clean <- master %>% 
  mutate(date = case_when(year == "2008" ~ "2008-05-01", # making the assumption that andrea's data was in April/May
                 year == "2007" ~ "2007-05-01", # fix andrea's
                 date == "02/20/2014"~ "2014-02-20", # fix andy's dates
                 date == "03/14/2014" ~ "2014-03-14", # fix andy's dates
                 date == "03/17/2014" ~ "2014-03-17", # fix andy's dates
                 TRUE ~ date)) %>% 
  mutate(date = ymd(date),
         month = substr(date,6,7),
         julian = format(date, "%j")) %>% 
  left_join(clim_regions_slim, by = c("location")) %>% 
  dplyr::select(collector, location, date, year,month, julian,
                lat, long,latitutdinal_region, climregion,
                tot, no_l, no_n, no_a,
                species,
                notes) %>% 
  mutate_at(vars(collector, location, latitutdinal_region, species), factor) %>% 
  mutate_at(vars(year, month,julian, tot,no_l, no_n, no_a), as.numeric) %>% 
  rename(climate_region = climregion,
         total_ticks = tot,
         total_l = no_l,
         total_n = no_n,
         total_a = no_a,
         lizard_species = species,
         lon = long) %>% 
    #filter(!is.na(latitutdinal_region)) %>% 
  mutate(latitutdinal_region = case_when(collector == "Young" ~ "central",
                                        TRUE ~ latitutdinal_region)) %>% 
  mutate(climate_region = case_when(collector == "MacDonald" ~ "South Coast",
                                  location  == "San Mateo" ~ "North Central",
                                  collector == "Young" ~ "San Joaquin Valley",
                                  collector == "Swei" ~ "North Central",
                                  location == "Big Creek" ~ "Central Coast",
                                  location == "Fort Ord"~ "Central Coast",
                                  location == "Hastings"~ "San Joaquin Valley", #changed
                                  location == "Rancho Marino"~ "Central Coast",
                                  location == "McLaughlin" ~ "North Central",
                                  location == "Quail Ridge" ~ "Sacramento-Delta",
                                  location == "Santa Cruz Island" ~ "South Coast",
                                  location == "Sedgwick"  ~ "South Coast",
                                  location == "Stunt Ranch"  ~ "South Coast",
                                  location == "Coal Oil Point" ~ "South Coast",
                                  location == "San Luis Obispo" ~ "Central Coast",
                                  location == "HOS" ~ "Sacramento-Delta",#changed
                                  location == "LFY" ~ "Sacramento-Delta",#changed
                                  location == "PR" ~ "Sacramento-Delta",#changed
                                  location  == "SLRP" ~ "North Central",#changed
                                  
                                  TRUE ~ "South Coast")) %>% 
  mutate(lizard_species = case_when(lizard_species == "Sceloporus " ~ "Sceloporus",
                                  lizard_species == "Sceloporous" ~ "Sceloporus",
                                  lizard_species == "Elgaria " ~ "Elgaria",
                                  lizard_species == "Uta.stansburia" ~ "Uta",
                                  TRUE ~ lizard_species))

master_clean$year[master_clean$year == "20"] <- 2019

#write.csv(master_clean, file= "data/master_clean_20241022.csv")


## climate full
climate_full_clean <- climate_full %>% 
  dplyr::select(-X) %>% 
  mutate(date = ymd(date)) %>% 
  mutate(season = case_when(month < 3 ~ "winter",
                            month < 7 ~ "spring",
                            month < 10 ~ "summer",
                            month < 13 ~ "fall",
                            TRUE ~ NA),
         julian = format(date, "%j")) %>% 
  mutate(season = factor(season, levels = c("spring",
                                               "summer",
                                               "fall",
                                               "winter"))) %>% 
  dplyr::select(location:month, season, julian,
                tmmn_daily:tmmx_winter)

#write.csv(climate_full_clean, file= "data/climate_full_clean_20241023.csv")

## climate monthly

master_clean %>% left_join(climate_full_clean2)

master_slim <- master_clean %>% dplyr::select(location, lat, lon, collector, date)

climate_full_clean2 <- master_slim %>% 
  left_join(climate_full_clean, by = c("lat","lon", "date")) %>% 
  group_by(lon, lat, date) %>% 
  mutate(julian = as.numeric(julian)) %>% 
  unique() #1,987


master_clean %>%  #2,170
  left_join(climate_full_clean2,by = c("lat","lon", "date")) %>%  #6,928
  group_by(lat, lon, date) %>% 
  unique() %>% slice(1)

merge(master_clean , climate_full_clean2 , by = c("lat", "lon","date"), all.x = TRUE) %>% unique() %>% 
  group_by("lat", "lon","date") %>% slice(1)
```

okay take subsets to see what the problem is
```{r}
arid <- climate_full_clean %>% 
  filter(location == "Arid") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "Arid")

intermediate <- climate_full_clean %>% 
  filter(location == "Intermediate") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "Intermediate")

mesic <- climate_full_clean %>% 
  filter(location == "Mesic") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "Mesic")

sedgwick <- 
climate_full_clean %>% 
  filter(location == "Sedgwick Reserve" |location ==  "Sedgwick") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "Sedgwick Reserve" |location ==  "Sedgwick")


SantaRosaIsland <- climate_full_clean %>% 
  filter(location == "Santa Rosa Island") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "Santa Rosa Island")


SantaCruzIsland <- climate_full_clean %>% 
  filter(location == "Santa Cruz Island") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "Santa Cruz Island")

SantaBarbara <- climate_full_clean %>% 
  filter(location == "Santa Barbara") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "Santa Barbara")

SanLuisObispo <- climate_full_clean %>% 
  filter(location == "San Luis Obispo") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "San Luis Obispo")


SanMateo <- climate_full_clean %>% 
  filter(location == "San Mateo") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "San Mateo")

SantaMonicaMountains <- climate_full_clean %>% 
  filter(location == "Santa Monica Mountains") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "Santa Monica Mountains")

CoalOilPoint <- climate_full_clean %>% 
  filter(location == "Coal Oil Point") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "Coal Oil Point")


StuntRanch <- climate_full_clean %>% 
  filter(location == "Stunt Ranch") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "Stunt Ranch")

McLaughlin <- climate_full_clean %>% 
  filter(location == "McLaughlin") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "McLaughlin")


QuailRidge <- climate_full_clean %>% 
  filter(location == "Quail Ridge") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "Quail Ridge")


FortOrd <- climate_full_clean %>% 
  filter(location == "Fort Ord") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "Fort Ord")

Hastings <- climate_full_clean %>% 
  filter(location == "Hastings") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "Hastings")

RanchoMarino <- climate_full_clean %>% 
  filter(location == "Rancho Marino") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "Rancho Marino")

BigCreek <- climate_full_clean %>% 
  filter(location == "Big Creek") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "Big Creek")


ParadiseRdburn <- climate_full_clean %>% 
  filter(location == "Paradise Rd burn") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "Paradise Rd burn")

ParadiseRdunburn <- climate_full_clean %>% 
  filter(location == "Paradise Rd unburn") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "Paradise Rd unburn")

# CCSP <- climate_full_clean %>% # no climate data
#   filter(location == "CCSP") %>% 
#   mutate(julian = as.numeric(julian)) %>% 
#   right_join(master_clean) %>% 
#   filter(location == "CCSP")
# 
# FL <- climate_full_clean %>% # no climate data
#   filter(location == "FL") %>% 
#   mutate(julian = as.numeric(julian)) %>% 
#   right_join(master_clean) %>% 
#   filter(location == "FL")

HOS <- climate_full_clean %>% 
  filter(location == "HOS") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "HOS")

LFY <- climate_full_clean %>% 
  filter(location == "LFY") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "LFY")

SLRP <- climate_full_clean %>% 
  filter(location == "SLRP") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "SLRP")

SMI  <- climate_full_clean %>% 
  filter(location == "SMI") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "SMI")


WDLP <- climate_full_clean %>% 
  filter(location == "WDLP") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "WDLP")

WH <- climate_full_clean %>% 
  filter(location == "WH") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "WH")

WP <- climate_full_clean %>% 
  filter(location == "WP") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "WP")

PUG <- climate_full_clean %>% 
  filter(location == "PUG") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "PUG")

TIL <- climate_full_clean %>% 
  filter(location == "TIL") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "TIL")

PR <- climate_full_clean %>% 
  filter(location == "PR") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "PR")

CC1 <- climate_full_clean %>% 
  filter(location == "CC1") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "CC1")

CC2 <- climate_full_clean %>% 
  filter(location == "CC2") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "CC2")

CC3 <- climate_full_clean %>% 
  filter(location == "CC3") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "CC3")

CC4 <- climate_full_clean %>% 
  filter(location == "CC4") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "CC4")

CC5 <- climate_full_clean %>% 
  filter(location == "CC5") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "CC5")

CC6 <- climate_full_clean %>% 
  filter(location == "CC6") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "CC6")

CC7 <- climate_full_clean %>% 
  filter(location == "CC7") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  right_join(master_clean) %>% 
  filter(location == "CC7")


## fix climate lacking locaitons - probs bc they are within 4km of another location 
# so using CC1 for MW sites and CCSP since they are geographically close
# i think this works to use CC1 climate data for MW1?
MW1 <- climate_full_clean %>% # 5,663
  filter(location == "CC1") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  mutate(location = case_when(location == "CC1" ~ "MW1",
                              TRUE ~ NA)) %>% 
  right_join(master_clean, "date") %>% 
  filter(location.y == "MW1") %>% 
  rename(location = location.x, 
         lon = lon.x,
         lat = lat.x,
         year = year.x,
         month = month.x,
         julian = julian.x) %>% 
  dplyr::select(location,lon, lat, date, year, month,
                season, julian,
                tmmn_daily:notes)%>% 
  dplyr::select(-c(location.y, year.y, month.y, julian.y, lat.y, lon.y))


MW2 <- climate_full_clean %>% # 5,663
  filter(location == "CC1") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  mutate(location = case_when(location == "CC1" ~ "MW2",
                              TRUE ~ NA)) %>% 
  right_join(master_clean, "date") %>% 
  filter(location.y == "MW2") %>% 
  rename(location = location.x, 
         lon = lon.x,
         lat = lat.x,
         year = year.x,
         month = month.x,
         julian = julian.x) %>% 
  dplyr::select(location,lon, lat, date, year, month,
                season, julian,
                tmmn_daily:notes)%>% 
  dplyr::select(-c(location.y, year.y, month.y, julian.y, lat.y, lon.y))


MW3 <- climate_full_clean %>% # 5,663
  filter(location == "CC1") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  mutate(location = case_when(location == "CC1" ~ "MW3",
                              TRUE ~ NA)) %>% 
  right_join(master_clean, "date") %>% 
  filter(location.y == "MW3") %>% 
  rename(location = location.x, 
         lon = lon.x,
         lat = lat.x,
         year = year.x,
         month = month.x,
         julian = julian.x) %>% 
  dplyr::select(location,lon, lat, date, year, month,
                season, julian,
                tmmn_daily:notes)%>% 
  dplyr::select(-c(location.y, year.y, month.y, julian.y, lat.y, lon.y))


MW4 <- climate_full_clean %>% # 5,663
  filter(location == "CC1") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  mutate(location = case_when(location == "CC1" ~ "MW4",
                              TRUE ~ NA)) %>% 
  right_join(master_clean, "date") %>% 
  filter(location.y == "MW4") %>% 
  rename(location = location.x, 
         lon = lon.x,
         lat = lat.x,
         year = year.x,
         month = month.x,
         julian = julian.x) %>% 
  dplyr::select(location,lon, lat, date, year, month,
                season, julian,
                tmmn_daily:notes)%>% 
  dplyr::select(-c(location.y, year.y, month.y, julian.y, lat.y, lon.y))

MW5 <- climate_full_clean %>% # 5,663
  filter(location == "CC1") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  mutate(location = case_when(location == "CC1" ~ "MW5",
                              TRUE ~ NA)) %>% 
  right_join(master_clean, "date") %>% 
  filter(location.y == "MW5") %>% 
  rename(location = location.x, 
         lon = lon.x,
         lat = lat.x,
         year = year.x,
         month = month.x,
         julian = julian.x) %>% 
  dplyr::select(location,lon, lat, date, year, month,
                season, julian,
                tmmn_daily:notes)%>% 
  dplyr::select(-c(location.y, year.y, month.y, julian.y, lat.y, lon.y))


MW6 <- climate_full_clean %>% # 5,663
  filter(location == "CC1") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  mutate(location = case_when(location == "CC1" ~ "MW6",
                              TRUE ~ NA)) %>% 
  right_join(master_clean, "date") %>% 
  filter(location.y == "MW6") %>% 
  rename(location = location.x, 
         lon = lon.x,
         lat = lat.x,
         year = year.x,
         month = month.x,
         julian = julian.x) %>% 
  dplyr::select(location,lon, lat, date, year, month,
                season, julian,
                tmmn_daily:notes)%>% 
  dplyr::select(-c(location.y, year.y, month.y, julian.y, lat.y, lon.y))


MW7 <- climate_full_clean %>% # 5,663
  filter(location == "CC1") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  mutate(location = case_when(location == "CC1" ~ "MW7",
                              TRUE ~ NA)) %>% 
  right_join(master_clean, "date") %>% 
  filter(location.y == "MW7") %>% 
  rename(location = location.x, 
         lon = lon.x,
         lat = lat.x,
         year = year.x,
         month = month.x,
         julian = julian.x) %>% 
  dplyr::select(location,lon, lat, date, year, month,
                season, julian,
                tmmn_daily:notes)%>% 
  dplyr::select(-c(location.y, year.y, month.y, julian.y, lat.y, lon.y))


CCSP <- climate_full_clean %>% # 5,663
  filter(location == "CC1") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  mutate(location = case_when(location == "CC1" ~ "CCSP",
                              TRUE ~ NA)) %>% 
  right_join(master_clean, "date") %>% 
  filter(location.y == "CCSP") %>% 
  rename(location = location.x, 
         lon = lon.x,
         lat = lat.x,
         year = year.x,
         month = month.x,
         julian = julian.x) %>% 
  dplyr::select(location,lon, lat, date, year, month,
                season, julian,
                tmmn_daily:notes)%>% 
  dplyr::select(-c(location.y, year.y, month.y, julian.y, lat.y, lon.y))


FL <- climate_full_clean %>% # 5,663
  filter(location == "PUG") %>% 
  mutate(julian = as.numeric(julian)) %>% 
  mutate(location = case_when(location == "PUG" ~ "FL",
                              TRUE ~ NA)) %>% 
  right_join(master_clean, "date") %>% 
  filter(location.y == "FL") %>% 
  rename(location = location.x, 
         lon = lon.x,
         lat = lat.x,
         year = year.x,
         month = month.x,
         julian = julian.x) %>% 
  dplyr::select(location,lon, lat, date, year, month,
                season, julian,
                tmmn_daily:notes) %>% 
  dplyr::select(-c(location.y, year.y, month.y, julian.y, lat.y, lon.y))



# 37.9683, -122.6043 (using these for MW sites - they'll be the same for all of them) - EXTRACT
# 37.4701, -122.3104 (using these for FL) - EXTRACT
# 38.0064, -122.4943 (using these for CCSP) - EXTRACT

```

Merge climate data together 
```{r}
unique(master_clean$location)

climate_filledin <- rbind(arid, intermediate, mesic, sedgwick, SantaRosaIsland, SantaCruzIsland,SantaBarbara,
      SanLuisObispo, SanMateo, SantaMonicaMountains, CoalOilPoint, StuntRanch, McLaughlin,
      QuailRidge, FortOrd, Hastings, RanchoMarino, BigCreek, ParadiseRdburn, ParadiseRdunburn,
      CCSP, FL, HOS, LFY, SLRP, SMI, WDLP, WH, WP, PUG, TIL, PR, CC1, CC2, CC3, CC4, CC5, CC6, CC7,
      MW1, MW2, MW3, MW4, MW5, MW6, MW7) 

```

filter dates for climate
```{r}
climate_filledin_filterdates <- climate_filledin %>% 
  inner_join(master_clean, by = c("location", "date")) %>% 
  group_by(location, date) %>% 
  slice(1) %>%
  rename(#location = location.x, 
         lon = lon.x,
         lat = lat.x,
         year = year.x,
         month = month.x,
         julian = julian.x) %>% 
  dplyr::select(location, 
                lon, lat, date, year, month, season, julian,
                tmmn_daily:tmmx_winter)
```

Add climate data to master list
```{r}
master_climate_full_withburn <- master_clean %>% 
  left_join(climate_filledin_filterdates,by = c("location", "date") ) %>% 
  rename(lon = lon.x,
         lat = lat.x,
         year = year.x,
         month = month.x,
         julian = julian.x)

#write.csv(master_climate_full_withburn,file ="data/clean/master_climate_full_withburn_20241013.csv")

master_climate_full <- master_clean %>% 
  left_join(climate_filledin_filterdates,by = c("location", "date") ) %>% 
  rename(lon = lon.x,
         lat = lat.x,
         year = year.x,
         month = month.x,
         julian = julian.x) %>% 
  filter(location != "Paradise Rd burn")

#write.csv(master_climate_full,file ="data/clean/master_climate_full_20241013.csv")
```

